<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.garsooon</groupId>
    <artifactId>DiscordCommandAlerter</artifactId>
    <version>1.1.0</version>

    <packaging>jar</packaging>

    <name>WorldEditAlerter</name>
    <description>Posts commands to a Discord channel via RMC DiscordCore</description>

    <properties>
        <maven.compiler.release>25</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>legacyminecraft-nexus-releases</id>
            <url>https://repository.legacyminecraft.com/repository/maven-public/</url>
        </repository>
        <repository>
            <id>legacyminecraft-nexus-snapshots</id>
            <url>https://repository.legacyminecraft.com/repository/maven-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.legacyminecraft</groupId>
            <artifactId>poseidon-api</artifactId>
            <version>2.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.retromc.discordcore.v6</groupId>
            <artifactId>DiscordCore-6</artifactId>
            <version>1.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.sk89q</groupId>
            <artifactId>worldedit</artifactId>
            <version>4.8.0</version>
        </dependency>
        <dependency>
            <groupId>com.johnymuffin.beta</groupId>
            <artifactId>discordauth</artifactId>
            <version>1.2.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>25</release>
                </configuration>
            </plugin>

        </plugins>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>
